### ISSUE TITLE
missing ros_pololu_servo.msg

### ISSUE THREAD

**Issue by linas** [geni-lab/ros_pololu_servo#8]
I am trying to run the hanson robotics basic_head_api but it crashes: aparantly, it uses the ros_pololu_servo.msg which was removed by Jamie Diprose somewhere along the way.   Other than stating the obvious: making backward-incompatible changes is evil, esp when you don't notify your dependent projects ... what can be done now?  What is the correct work-around for this?

Part of the problem is that Hanson Robotics failed to track the changes in this repo, but removing a previously supported message without warning is also .. a bad thing.  

I opened a matching bug report on the other side: See https://github.com/hansonrobotics/basic_head_api/issues/3

**Comment by jdddog** [comment]
Did you sort everything out / can I close this?

**Comment by linas** [comment]
Above, you state:
```
Here are examples of:

    how to program it

    how to launch it

    how to write a config file
```
This info belongs in the README file, and not buried in a closed bug report.  J ust made a pull request #10 for this

**Comment by linas** [comment]
Oh  closing. basic_head_api which prompted this, is now obsolete.
